<?php
//Private settings, Do not commit to public repos.

// Simply define below constants.

define('IDEAL_URL', 'https://www.ideal-simulator.nl/lite/');

define('MERCHANT_ID', '123456789');
define('SUB_ID', '0');
define('HASH_KEY', 'Password');
define('AQUIRER_NAME', 'Piratenpartij');
define('AQUIRER_URL', 'http://piratenpartij.nl');

define('DB_HOST', 'localhost');
define('DB_USER', 'drupal');
define('DB_PASS', 'drupal');
define('DB_NAME', 'lidworden_development');

define('DEFAULT_AMOUNT', '17.50');

define('EMAIL_TO', "secretaris <ber@webschuur.com>");
