
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <aside class="grid-4 region region-sidebar-first"
            id="region-sidebar-first">
              <div class="region-inner region-sidebar-first-inner">
                <section class="block block-block block-9 block-block-9 odd"
                id="block-block-9">
                  <div class="block-inner clearfix">
                    <h2 class="block-title">Help</h2>
                    <div class="content clearfix">
                      <p>
                        Om lid te worden, hebben we je adres, woonplaats en volledige naam nodig. Je kunt hier met iDeal betalen. Wil je op een andere manier betalen, kijk dan op <a href="http://www.piratenpartij.nl/lid-worden">de homepage voor meer informatie en contactgegevens</a>.
                      <p>
                      <p>
                      De Piratenpartij schrijft je graag in als lid van de partij. 
                      De kosten daarvan bedragen 17,50 euro per kalenderjaar.
                      Als lid heb je een stem op de jaarlijkse Algemene Leden Vergadering.
                      Daarnaast ben je welkom op alle informele en formele bijeenkomsten van de Piratenpartij.
                      Ook telt het aantal leden van een politieke partij mee bij het bepalen van de subsidies voor onder andere wetenschappelijk onderzoek.
                      <p>
                    </div>
                  </div>
                </section>
              </div>
            </aside>
          </div>
        </div>
      </section>
      <footer id="section-footer" class="section section-footer">
        <div id="zone-footer-wrapper"
        class="zone-wrapper zone-footer-wrapper clearfix">
          <div id="zone-footer"
          class="zone zone-footer clearfix container-12">
            <div class="grid-8 region region-footer-first-left"
            id="region-footer-first-left">
              <div class="region-inner region-footer-first-left-inner">
                <div></div>
                <div style="clear: both;">&#160;</div>
              </div>
            </div>
            <div class="grid-4 region region-footer-first-right"
            id="region-footer-first-right">
              <div class="region-inner region-footer-first-right-inner">

                <h3 class="ppnl-info-title">Piratenpartij
                Nederland</h3>
                <div>
                  <ul class="ppnl-info-links">
                    <li>
                      <a href="http://www.piratenpartij.nl/contact">Contact</a>
                    </li>
                    <li>
                      <a href="http://www.piratenpartij.nl/sponsoren">Sponsoren</a>
                    </li>
                    <li>
                      <a href="http://www.piratenpartij.nl/privacy-verklaring">
                      Privacyverklaring</a>
                    </li>
                    <li>
                      <a href="https://creativecommons.org/licenses/by-sa/3.0/deed.nl">
                      CC-BY-SA 3.0</a>
                    </li>
                  </ul>
                </div>
                <div style="clear: both;">&#160;</div>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>
